name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: warren-davies4
          base: master
          head: master